### ISSUE TITLE
Missing instructions in the README?

### ISSUE THREAD

**Issue by joshhornby** [AltThree/Bugsnag#2]
I am trying to use this package with https://github.com/AltThree/Logger, after I add the service provider do I need to add anything into the [Logger config file](https://github.com/AltThree/Logger/blob/master/config/logger.php)?

I have also ran `php artisan vendor:publish` and added my API key for Bugsnag but I think I am missing something as this doesn't work.

Thanks

**Comment by GrahamCampbell** [comment]
Yes.

**Comment by GrahamCampbell** [comment]
Example:

```
<?php

declare(strict_types=1);

/*
 * This file is part of Alt Three StyleCI.
 *
 * (c) Alt Three Services Limited
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

return [

    /*
    |--------------------------------------------------------------------------
    | Loggers
    |--------------------------------------------------------------------------
    |
    | Here are each of the loggers to call under the hood while logging.
    |
    */

    'loggers' => env('APP_DEBUG', false) ? ['Illuminate\Log\Writer' => ['*']] : [
        'AltThree\Bugsnag\Logger' => ['error', 'critical', 'alert', 'emergency'],
        'AltThree\Logify\Logger'  => ['*'],
    ],

];
```

**Comment by GrahamCampbell** [comment]
That is if you want to use that package.

**Comment by GrahamCampbell** [comment]
> something as this doesn't work.

What exactly doesn't work. Note that the `log` function will never work due to the way laravel works.

**Comment by GrahamCampbell** [comment]
That's the glovbal function btw.

**Comment by GrahamCampbell** [comment]
Exception logging, and logging by injecting a psr logger interface should work just fine though.

**Comment by joshhornby** [comment]
Perfect. This now works as expected, thanks.

**Comment by Sly-Ripper** [comment]
"'AltThree\Logify\Logger'  => ['*']" causes: PHP Fatal error: Uncaught ReflectionException: Class AltThree\Logify\Logger does not exist

If I remove that, Bugsnag receives the error. What's wrong here?

**Comment by GrahamCampbell** [comment]
Looks like you forgot to install that logify package.

**Comment by GrahamCampbell** [comment]
> If I remove that, Bugsnag receives the error. What's wrong here?

Yeh, you can't use logify. It's not an open source repo. It was merely an example for demonstration. You don't need to include it to have bugsnag work.

**Comment by Sly-Ripper** [comment]
Awesome, thanks.

**Comment by GrahamCampbell** [comment]
Logify basically is what we use to hook things up to our internal logging system so we can log debug and info messages that aren't suitable for bugsnag.
