### ISSUE TITLE
White blank page if debug if false + Does not report to BugSnag

### ISSUE THREAD

**Issue by canfiax** [AltThree/Bugsnag#5]
I am visiting a page, and all I get is a blank page.

I check bugsnag and nothing is there.

I have filled out my bugsnag api code.

Unable how to debug further.

**Comment by canfiax** [comment]
I am also using your Logging package.

    'loggers' => env('APP_DEBUG', false) ? ['Illuminate\Log\Writer' => ['*']] : [
        'AltThree\Bugsnag\Logger'   => ['error', 'critical', 'alert', 'emergency'],
        'AltThree\Logify\Logger'    => ['*']
    ],

**Comment by GrahamCampbell** [comment]
Of course it doesn't. What else did you expect that code to do that I gave you?

**Comment by GrahamCampbell** [comment]
Wait, you're saying it's broken. Please provide php level error logs then/

**Comment by GrahamCampbell** [comment]
You're saying it's broken when not in debug mode, rather than not logging when in debug mode, as expected.

**Comment by canfiax** [comment]
I fixed it! I had to delete folder /bootstrap/compiled.php

**Comment by GrahamCampbell** [comment]
You MUST run `php artisan config:cache` and `php artisan optimize --force` after making changes to composer or config.

**Comment by GrahamCampbell** [comment]
That's always true for laravel.
