### ISSUE TITLE
bugsnag not reporting a specfic error

### ISSUE THREAD

**Issue by ctf0** [AltThree/Bugsnag#6]
hey again :),
am hosting an app over a cpanel "yeah i know" however for a specific error , bugsnag doesn't log it, its not a big deal, i already fixed the issue but i just want to know why BS doesn't log something like that, so..

config/logger
```php
'loggers' => env('APP_DEBUG', false)
    ? ['Illuminate\Log\Writer' => ['*']]
    : ['AltThree\Bugsnag\Logger' => ['*']], // hopefully to log everything
```

here is the whoops debug
![test](https://cloud.githubusercontent.com/assets/7388088/16712134/487a6acc-467d-11e6-9dc2-59a82b19f8ef.jpg)

the good thing that i don't get the normal whoops page when the error occur , so something like 
```php
public function render($request, Exception $e)
{
    if ($e instanceof FatalErrorException && App::environment('production')) {
        return response()->view('errors.500', [], 500);
    }

    return parent::render($request, $e);
}
```
is unnecessary instead i get the browser 500 error page which is good, but still don't know why BS ignore such an error. 

i know BS is working because it logged an error about `PDOException` days earlier without any issues.

**Comment by GrahamCampbell** [comment]
I don't think this is a problem with this library?

**Comment by ctf0** [comment]
i don't exactly know, thats why i came here asking, does the lib ignore the fatal exceptions ? do i need to change something in the settings of bs ? do i need to add something to the app/handler ?

**Comment by GrahamCampbell** [comment]
It should handle them since we're doing nothing at all with the exception handler. It's just laravel's native one. Nothing to add. If it's not handling them, it's unrelated. All we're doing is rebinding the logger.

**Comment by ctf0** [comment]
not to beat a dead horse, but if whoops can log the error shouldn't bs do the same as well ?
