### ISSUE TITLE
package doesnt work with BS anymore after last update

### ISSUE THREAD

**Issue by ctf0** [AltThree/Bugsnag#7]
everything was working just perfect b4 the latest update of BS , but after the latest changes they  made ,now nothing is being reported to BS and all am getting on the dashboard is 

![test copy](https://cloud.githubusercontent.com/assets/7388088/17084113/df278f3e-51b5-11e6-9969-957c9f56f49c.jpg)

**Comment by GrahamCampbell** [comment]
This package isn't anything to do with the offical bugsnag package, and their docs don't apply there at all.

**Comment by GrahamCampbell** [comment]
The point of this package was to provide a psr logger only.

**Comment by GrahamCampbell** [comment]
I've since implemented an official version over on the bugsnag org. The docs on the website are still out of sync there. We have an internal PR to update them for the new packages.

**Comment by ctf0** [comment]
i know that the package have nothing to do with the official BS package , but maybe something change in the implementation and u need to update the package to reflect that change so everything goes back to working like b4.

**Comment by GrahamCampbell** [comment]
I don't see what would have broken?

**Comment by GrahamCampbell** [comment]
And, what latest update please?

**Comment by ctf0** [comment]
here is from the update emails i got over my email
http://blog.bugsnag.com/php-notifier-update

b4 that email "or that updates" ur package was reporting working without any issues, but now nothing but the above img.

**Comment by GrahamCampbell** [comment]
This package does not use the new version.

**Comment by GrahamCampbell** [comment]
Sorry I'm not being very helpful. The plan is to officially mark this package as abandoned, replaced by the new bugsnag packages.

**Comment by ctf0** [comment]
okay, the question is 
will replacing this with the new BS package will still work the same as b4,
whoops on local, bs on production ?

**Comment by GrahamCampbell** [comment]
Yes, it will work in a similar way.

**Comment by GrahamCampbell** [comment]
One sec, I can screenshot a diff upgrading a private codebase to the new library for you...

**Comment by ctf0** [comment]
that would be awesome

**Comment by GrahamCampbell** [comment]
![image](https://cloud.githubusercontent.com/assets/2829600/17084493/129babce-51b7-11e6-90e0-40ccf8084f6c.png)
![image](https://cloud.githubusercontent.com/assets/2829600/17084494/1a3a0ed4-51b7-11e6-94fa-a5310bad3d36.png)

You'll need to republish the config file, and update the psr logger bindings too. If you're using this package with the alt-three logger package, you can just update it's config file with the new psr logger class, otherwise, just follow the guide on the offical bugsnag docs.

**Comment by ctf0** [comment]
okay so here is everything , plz confirm if i need to change/add something
```js
// composer
"bugsnag/bugsnag-laravel":"^2.0",
"alt-three/logger": "^1.2",
```
```php
// config/logger
'loggers' => env('APP_DEBUG')
    ? ['Illuminate\Log\Writer' => ['*']]
    : ['Psr\Log\LoggerInterface' => ['*']],

// app/exception
use GrahamCampbell\Exceptions\ExceptionHandler as ExceptionHandler;
```
removed the old `config/bugsnag` and republished the config

do i need the `alt-three/logger` or should i remove it ?

**Comment by ctf0** [comment]
add the `Reporting unhandled exceptions part` with **bugsnag.multi** instead of single and updated the logger to
```php
 'loggers' => env('APP_DEBUG')
    ? ['Illuminate\Log\Writer' => ['*']]
    : [
        app()->alias('bugsnag.multi', Log::class) => ['*'],
        app()->alias('bugsnag.multi', LoggerInterface::class) => ['*'],
    ],
```

not sure if this is right or wrong, testing with `abort(404)` doesnt report to BS 😞

**Comment by GrahamCampbell** [comment]
No, you don;'t need to do that! Also, this was not working because you never register the logger, so it never worked.

**Comment by GrahamCampbell** [comment]
You don't need alt-three's logger package.

**Comment by ctf0** [comment]
am kinda lost , so basicly ur exception package handle this automatically
whoops for debug=true , bs for debug=false ?

**Comment by GrahamCampbell** [comment]
It doesn;t do it automatically if you don't bind the logger correctly.

**Comment by GrahamCampbell** [comment]
This package will do nothing automatically out of the box.

**Comment by ctf0** [comment]
okay, can u then tell me how to bind the logger correctly to achieve the above goal ?

**Comment by GrahamCampbell** [comment]
If you ditch the alt-three logger package, then just exactly follow the docs I wrote on docs.bugsnag.com.

**Comment by ctf0** [comment]
it seems that for some reason its dam hard to understand my what am after so thanx anyway.

**Comment by ctf0** [comment]
the solution is
```php
public function register()
{
    if ( ! env('APP_DEBUG')) {
        $this->app->alias('bugsnag.logger', Log::class);
        $this->app->alias('bugsnag.logger', LoggerInterface::class);
    }
}
```
having the `bugsnag.multi` is impractical because now both bs and whoops will do the same while mostly u just need bs to work when u cant access whoops 'ex production or debug=false` 

so maybe it would be better if we tweaked the underline of the **multi** to work only in those 2 cases so the user doesn't need to add any extra lines and bs works exactly as u would think.

thanks for all ur hard work.

**Comment by GrahamCampbell** [comment]
> having the bugsnag.multi is impractical because now both bs and whoops will do the same while 

Some people want to log to both places in production though, that's why we have that. Some people also don't, and we accomodate that too.

**Comment by GrahamCampbell** [comment]
I think your current code there looks pretty good. We don't want to restrict things anymore than we have so people can get the exact setup they want.
